Add OCI Artifacts manifest type
notaryproject/artifacts pull request #3
Opened 2021-03-24 08:16 UTC by aviral26

This PR adds a new type, `Artifact`, that describes a manifest for an OCI artifact. Spec available here: https://github.com/opencontainers/artifacts/pull/29

2021-03-24 08:25 UTC, shizhMSFT requested changes

2021-03-24 08:25 UTC, shizhMSFT commented on go.mod
> +go 1.15
The latest is `1.16`

2021-03-24 08:25 UTC, shizhMSFT commented on specs-go/v2/artifact.go
> +	Config Descriptor `json:"config"`
`config` is optional. Should we take `*Descriptor` instead of `Descriptor`?

2021-03-24 08:25 UTC, shizhMSFT commented on specs-go/v2/artifact.go
> +	Config Descriptor `json:"config"`
If it is empty, should we do `omitempty`?

2021-03-24 08:25 UTC, shizhMSFT commented on specs-go/v2/mediatype.go
> +	MediaTypeArtifact = "application/vnd.oci.artifact.manifest.v1+json"
Should it be `MediaTypeArtifact` or `MediaTypeArtifactManifest`?

2021-03-24 09:46 UTC, aviral26 commented on go.mod
> +go 1.15
Addressed

2021-03-24 09:47 UTC, aviral26 commented on specs-go/v2/artifact.go
> +	Config Descriptor `json:"config"`
Yes, makes sense

2021-03-24 09:47 UTC, aviral26 commented on specs-go/v2/mediatype.go
> +	MediaTypeArtifact = "application/vnd.oci.artifact.manifest.v1+json"
Addressed

2021-03-24 09:57 UTC, shizhMSFT approved these changes
LGTM

2021-03-25 20:16 UTC, merged

2021-03-25 20:18 UTC, SteveLasker commented
@aviral26, can you move this PR to the [artifacts v1.0-stage branch](https://github.com/opencontainers/artifacts/tree/v1.0-stage)
Once done, we'll remove this fork and track OCI Artifact and subsequent manifest changes there.